config/routes.rb
Rails.application.routes.draw do
  root 'main#index'
  resources :products, only: [:show]
  resources :categories, only: [:show] do
    resources :sub_categories, only: [:show] do
      resources :sub_sub_categories, only: [:show]
    end
  end

  namespace :admin do
    root 'main#index'
    resources :products
    resources :categories do
      resources :sub_categories do
        resources :sub_sub_categories
      end
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :sub_categories, dependent: :destroy
	has_many :products, through: :sub_categories

  validates :name, uniqueness: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :sub_sub_category

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true, length: { minimum: 140 }
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
  belongs_to :category
	has_many :sub_sub_categories, dependent: :destroy
	has_many :products, through: :sub_sub_categories

  validates :name, presence: true
end

app/models/sub_sub_category.rb
class SubSubCategory < ApplicationRecord
  belongs_to :sub_category
	has_many :products, dependent: :destroy

  validates :name, presence: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  def index
    @products = Product.all
    @categories = Category.all.order('id ASC')
    @sub_categories = SubCategory.all
    @sub_sub_categories = SubSubCategory.all
  end

  def show
    @category = Category.find(params[:id])
    @sub_category = SubCategory.where(category_id: params[:id])
    @sub_sub_category = SubSubCategory.where(sub_category_id: @sub_category.ids)

    @products = Product.where(sub_sub_category_id: @sub_sub_category.ids)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

   if @category.save
     redirect_to admin_categories_path, notice: 'Category was successfully created.'
   else
     render :new
   end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      redirect_to admin_categories_path, notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])

    @category.destroy
    redirect_to admin_categories_path, notice: 'Category was successfully deleted.'
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/admin/main_controller.rb
class Admin::MainController < ApplicationController
  def index
    @products = Product.all.order('id ASC')
    @categories = Category.all
    @sub_categories = SubCategory.all
    @sub_sub_categories = SubSubCategory.all

  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  def show
    @categories = Category.all
    @sub_categories = SubCategory.all
    @sub_sub_categories = SubSubCategory.all


    @product = Product.find(params[:id])

    @sub_sub_category = SubSubCategory.find_by(id: @product.sub_sub_category_id)

    @sub_category = SubCategory.find_by(id: @sub_sub_category.sub_category_id)

    @category = Category.find_by(id: @sub_category.category_id)
  end
  def new
    @product = Product.new
    @sub_categories = SubCategory.all
  end

  def create
    @product = Product.new(product_params)

   if @product.save
     redirect_to admin_product_path(@product), notice: 'Product was successfully created.'
   else
     render :new
   end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to admin_product_path(@product), notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])

    @product.destroy
    redirect_to admin_root_path, notice: 'Product was successfully deleted.'
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price, :sub_sub_category_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show

    @categories = Category.all
    @sub_categories = SubCategory.all
    @sub_sub_categories = SubSubCategory.all


    @category = Category.find(params[:id])
    @sub_category = SubCategory.where(category_id: params[:id])
    @sub_sub_category = SubSubCategory.where(sub_category_id: @sub_category.ids)

    @products = Product.where(sub_sub_category_id: @sub_sub_category.ids)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @products = Product.all
    @categories = Category.all
    @sub_categories = SubCategory.all
    @sub_sub_categories = SubSubCategory.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show
    @categories = Category.all
    @sub_categories = SubCategory.all
    @sub_sub_categories = SubSubCategory.all

    @product = Product.find(params[:id])

    @sub_sub_category = SubSubCategory.find_by(id: @product.sub_sub_category_id)

    @sub_category = SubCategory.find_by(id: @sub_sub_category.sub_category_id)

    @category = Category.find_by(id: @sub_category.category_id)

  end
end

app/controllers/sub_categories_controller.rb
class SubCategoriesController < ApplicationController
  def show
    @categories = Category.all
    @sub_categories = SubCategory.all
    @sub_sub_categories = SubSubCategory.all

    @category = Category.find(params[:category_id])
    @sub_category = SubCategory.find(params[:id])
    @sub_sub_category = SubSubCategory.where(sub_category_id: @sub_category)

    @products = Product.where(sub_sub_category_id: @sub_sub_category.ids)
  end
end

app/controllers/sub_sub_categories_controller.rb
class SubSubCategoriesController < ApplicationController
  def show
    @categories = Category.all
    @sub_categories = SubCategory.all
    @sub_sub_categories = SubSubCategory.all

    @category = Category.find(params[:category_id])
    @sub_category = SubCategory.find(params[:sub_category_id])

    @sub_sub_category = SubSubCategory.find(params[:id])

    @products = Product.where(sub_sub_category_id: @sub_sub_category)
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/main_helper.rb
module Admin::MainHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/admin/sub_categories_helper.rb
module Admin::SubCategoriesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sub_categories_helper.rb
module SubCategoriesHelper
end

app/helpers/sub_sub_categories_helper.rb
module SubSubCategoriesHelper
end

app/views/admin/main/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/admin">sephora</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
          <li><a href="/admin/categories" role="button" aria-haspopup="true" aria-expanded="false">Manage Categories</a></li>
          <li><a href="/admin" role="button" aria-haspopup="true" aria-expanded="false">Manage Products</a></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Normal User', root_path %></li>
      </ul>


    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/admin/main/index.html.erb
<%= render 'admin/main/header' %>

<div class="col-md-12">
<%= link_to 'new product', new_admin_product_path, class:"btn btn-info" %>
</div>
<% @products.each do |product| %>
<div class="col-md-8" style="padding: 10px 20px">
  <h1>
    <%= product.name %>
      <small>
        <%= product.price %>
      </small>
  </h1>
  <p>
    <%= product.description %>
  </p>


</div>

<div class="col-md-4" style="padding: 20px 20px">
  <h1>
  <%= link_to 'show', admin_product_path(product), class:"btn btn-default" %>
  <%= link_to 'edit', edit_admin_product_path(product), class:"btn btn-warning" %>
  <%= link_to 'delete', admin_product_path(product), method: :delete, class:"btn btn-danger" %>

  </h1>
</div>

<% end %>

app/views/main/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">sephora</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <% @categories.order('id ASC').each do |category| %>

        <li class="dropdown">
          <a href="/categories/<%= category.id %>" role="button" aria-haspopup="true" aria-expanded="false"><%= category.name %></a>


          <ul class="dropdown-menu">

            <% @sub_categories.each do |sub_cat| %>
              <% if sub_cat.category_id == category.id %>
              <li><a href="/categories/<%= category.id %>/sub_categories/<%= sub_cat.id %>"><%= sub_cat.name %></a></li>

              <% @sub_sub_categories.each do |sub_sub_cat| %>
              <% if sub_sub_cat.sub_category_id == sub_cat.id %>
                <li><a href="/categories/<%= category.id %>/sub_categories/<%= sub_cat.id %>/sub_sub_categories/<%= sub_sub_cat.id %>">> <%= sub_sub_cat.name %></a></li>
              <% end %>
              <% end %>

            <% end %>
            <% end %>
          </ul>
        </li>
        <% end %>

      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Admin', admin_root_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/main/index.html.erb
<%= render 'main/header' %>
<h1>All Products</h1>


<% @products.each do |product| %>
  <div class="col-md-4" style="padding: 0px 20px; height: 400px">
    <h1>
      <a href="/products/<%= product.id %>" style="color: black"><%= product.name %></a>
        <small>
          <%= product.price %>
        </small>
    </h1>
    <p>
      <%= product.description %>
    </p>
  </div>
<% end %>