config/routes.rb
Rails.application.routes.draw do
  root 'main#index'
  resources :products, only: [:show]
  resources :categories, only: [:show] do
    resources :sub_categories, only: [:show] do
      resources :sub_sub_categories, only: [:show]
    end
  end

  namespace :admin do
    root 'main#index'
    resources :products
    resources :categories do
      resources :sub_categories do
        resources :sub_sub_categories
      end
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
  belongs_to :category
	has_many :sub_sub_categories, dependent: :destroy
	has_many :products, through: :sub_sub_categories

  validates :name, presence: true
end

app/controllers/admin/sub_categories_controller.rb
class Admin::SubCategoriesController < ApplicationController
  def new
    @category = Category.find(params[:category_id])
    @sub_category = SubCategory.new
  end

  def create
    @category = Category.find(params[:category_id])
    @sub_category = SubCategory.new(sub_category_params)

   if @sub_category.save
     redirect_to admin_categories_path, notice: 'SubCategory was successfully created.'
   else
     render :new
   end
  end

  def edit
    @category = Category.find(params[:category_id])
    @sub_category = SubCategory.find(params[:id])
  end

  def update
    @category = Category.find(params[:category_id])
    @sub_category = SubCategory.find(params[:id])


    if @sub_category.update(sub_category_params)
      redirect_to admin_categories_path, notice: 'SubCategory was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:category_id])
    @sub_category = SubCategory.find(params[:id])

    @sub_category.destroy
    redirect_to admin_categories_path, notice: 'SubCategory was successfully deleted.'
  end

  def show
    @category = Category.find(params[:category_id])
    @sub_category = SubCategory.find(params[:id])
    @sub_sub_category = SubSubCategory.where(sub_category_id: @sub_category.id)

    @products = Product.where(sub_sub_category_id: @sub_sub_category.ids)
  end

  private

  def sub_category_params
    params.require(:sub_category).permit(:name, :category_id)
  end
end

app/controllers/sub_categories_controller.rb
class SubCategoriesController < ApplicationController
  def show
    @categories = Category.all
    @sub_categories = SubCategory.all
    @sub_sub_categories = SubSubCategory.all

    @category = Category.find(params[:category_id])
    @sub_category = SubCategory.find(params[:id])
    @sub_sub_category = SubSubCategory.where(sub_category_id: @sub_category)

    @products = Product.where(sub_sub_category_id: @sub_sub_category.ids)
  end
end

app/helpers/admin/sub_categories_helper.rb
module Admin::SubCategoriesHelper
end

app/helpers/sub_categories_helper.rb
module SubCategoriesHelper
end

app/views/admin/sub_categories/edit.html.erb
<%= render 'admin/main/header' %>

<div class="form-container" style="width: 60%">
  <h1>Edit SubCategory</h1>

  <%= form_for @sub_category, url: admin_category_sub_category_path(params[:category_id]) do |f| %>


    <div class="form-group">
    	<%= f.label :name %>
    	<%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
    	<%= f.submit :class => "btn btn-default"%>
    </div>


  <% end %>

  <br><br>

  <%= link_to 'Back to Categories', admin_categories_path %>
  <br>
  <%= link_to 'Back to All Products', admin_root_path %>

</div>

app/views/admin/sub_categories/new.html.erb
<%= render 'admin/main/header' %>

<div class="form-container" style="width: 60%">
  <h1>New SubCategory in <%= @category.name %></h1>

  <%= @sub_category.errors.full_messages %>

  <%= form_for @sub_category, url: admin_category_sub_categories_path(params[:category_id]) do |f| %>


    <div class="form-group">
    	<%= f.label :name %>
    	<%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
    	<%= f.hidden_field :category_id, class: "form-control", value: @category.id %>
    </div>

    <div class="form-group">
    	<%= f.submit :class => "btn btn-default"%>
    </div>


  <% end %>

  <br><br>

  <%= link_to 'Back to Categories', admin_categories_path %>
  <br>
  <%= link_to 'Back to All Products', admin_root_path %>

</div>

app/views/admin/sub_categories/show.html.erb
<%= render 'admin/main/header' %>

<h1>All Products with</h1>
<h2>Category: <a href="/admin/categories/<%= @category.id %>"><%= @category.name %></a></h2>
<h2>SubCategory: <%= @sub_category.name %></h2>


<% @products.each do |product| %>
<div class="col-md-4" style="padding: 0px 20px; height: 400px">
  <h1>
    <a href="/admin/products/<%= product.id %>" style="color: black"><%= product.name %></a>
      <small>
        <%= product.price %>
      </small>
  </h1>
  <p>
    <%= product.description %>
  </p>

  <%= link_to 'edit', edit_admin_product_path(product), class:"btn btn-lg" %>
  <%= link_to 'delete', admin_product_path(product), method: :delete, class:"btn btn-lg" %>


</div>

<% end %>