config/routes.rb
Rails.application.routes.draw do
  root 'main#index'
  resources :products, only: [:show]
  resources :categories, only: [:show] do
    resources :sub_categories, only: [:show] do
      resources :sub_sub_categories, only: [:show]
    end
  end

  namespace :admin do
    root 'main#index'
    resources :products
    resources :categories do
      resources :sub_categories do
        resources :sub_sub_categories
      end
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :sub_categories, dependent: :destroy
	has_many :products, through: :sub_categories

  validates :name, uniqueness: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :sub_sub_category

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true, length: { minimum: 140 }
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
  belongs_to :category
	has_many :sub_sub_categories, dependent: :destroy
	has_many :products, through: :sub_sub_categories

  validates :name, presence: true
end

app/models/sub_sub_category.rb
class SubSubCategory < ApplicationRecord
  belongs_to :sub_category
	has_many :products, dependent: :destroy

  validates :name, presence: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  def index
    @products = Product.all
    @categories = Category.all.order('id ASC')
    @sub_categories = SubCategory.all
    @sub_sub_categories = SubSubCategory.all
  end

  def show
    @category = Category.find(params[:id])
    @sub_category = SubCategory.where(category_id: params[:id])
    @sub_sub_category = SubSubCategory.where(sub_category_id: @sub_category.ids)

    @products = Product.where(sub_sub_category_id: @sub_sub_category.ids)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

   if @category.save
     redirect_to admin_categories_path, notice: 'Category was successfully created.'
   else
     render :new
   end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      redirect_to admin_categories_path, notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])

    @category.destroy
    redirect_to admin_categories_path, notice: 'Category was successfully deleted.'
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/admin/main_controller.rb
class Admin::MainController < ApplicationController
  def index
    @products = Product.all.order('id ASC')
    @categories = Category.all
    @sub_categories = SubCategory.all
    @sub_sub_categories = SubSubCategory.all

  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  def show
    @categories = Category.all
    @sub_categories = SubCategory.all
    @sub_sub_categories = SubSubCategory.all


    @product = Product.find(params[:id])

    @sub_sub_category = SubSubCategory.find_by(id: @product.sub_sub_category_id)

    @sub_category = SubCategory.find_by(id: @sub_sub_category.sub_category_id)

    @category = Category.find_by(id: @sub_category.category_id)
  end
  def new
    @product = Product.new
    @sub_categories = SubCategory.all
  end

  def create
    @product = Product.new(product_params)

   if @product.save
     redirect_to admin_product_path(@product), notice: 'Product was successfully created.'
   else
     render :new
   end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to admin_product_path(@product), notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])

    @product.destroy
    redirect_to admin_root_path, notice: 'Product was successfully deleted.'
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price, :sub_sub_category_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show

    @categories = Category.all
    @sub_categories = SubCategory.all
    @sub_sub_categories = SubSubCategory.all


    @category = Category.find(params[:id])
    @sub_category = SubCategory.where(category_id: params[:id])
    @sub_sub_category = SubSubCategory.where(sub_category_id: @sub_category.ids)

    @products = Product.where(sub_sub_category_id: @sub_sub_category.ids)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @products = Product.all
    @categories = Category.all
    @sub_categories = SubCategory.all
    @sub_sub_categories = SubSubCategory.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show
    @categories = Category.all
    @sub_categories = SubCategory.all
    @sub_sub_categories = SubSubCategory.all

    @product = Product.find(params[:id])

    @sub_sub_category = SubSubCategory.find_by(id: @product.sub_sub_category_id)

    @sub_category = SubCategory.find_by(id: @sub_sub_category.sub_category_id)

    @category = Category.find_by(id: @sub_category.category_id)

  end
end

app/controllers/sub_categories_controller.rb
class SubCategoriesController < ApplicationController
  def show
    @categories = Category.all
    @sub_categories = SubCategory.all
    @sub_sub_categories = SubSubCategory.all

    @category = Category.find(params[:category_id])
    @sub_category = SubCategory.find(params[:id])
    @sub_sub_category = SubSubCategory.where(sub_category_id: @sub_category)

    @products = Product.where(sub_sub_category_id: @sub_sub_category.ids)
  end
end

app/controllers/sub_sub_categories_controller.rb
class SubSubCategoriesController < ApplicationController
  def show
    @categories = Category.all
    @sub_categories = SubCategory.all
    @sub_sub_categories = SubSubCategory.all

    @category = Category.find(params[:category_id])
    @sub_category = SubCategory.find(params[:sub_category_id])

    @sub_sub_category = SubSubCategory.find(params[:id])

    @products = Product.where(sub_sub_category_id: @sub_sub_category)
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/main_helper.rb
module Admin::MainHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/admin/sub_categories_helper.rb
module Admin::SubCategoriesHelper
end

app/helpers/admin/sub_sub_categories_helper.rb
module Admin::SubSubCategoriesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sub_categories_helper.rb
module SubCategoriesHelper
end

app/helpers/sub_sub_categories_helper.rb
module SubSubCategoriesHelper
end

app/views/admin/categories/edit.html.erb
<%= render 'admin/main/header' %>

<div class="form-container" style="width: 60%">
  <h1>Edit Category</h1>

  <%= form_for @category, url: admin_category_path(params[:id]) do |f| %>


    <div class="form-group">
    	<%= f.label :name %>
    	<%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
    	<%= f.submit :class => "btn btn-default"%>
    </div>


  <% end %>

  <br><br>

  <%= link_to 'Back to Categories', admin_categories_path %>
  <br>
  <%= link_to 'Back to All Products', admin_root_path %>

</div>

app/views/admin/categories/index.html.erb
<%= render 'admin/main/header' %>

<div id="notice">
<% flash.each do |key, value| %>
  <div class="alert alert-info" role="alert">
    <%= value %>
  </div>
<% end %>
</div>

<%= link_to 'new category', new_admin_category_path, class:"btn btn-info" %>

<table class="table table-sm">
  <thead>
    <tr>
      <th>Category Name (click to toggle)</th>
      <th>Category ID</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>

    <% @categories.each do |category| %>

    <tr class="accordion-toggle" data-toggle="collapse" data-target="#<%= category.name %>-cores">
      <td><%= category.name %></td>
      <td><%= category.id %></td>
      <td>
        <%= link_to 'show', admin_category_path(category), class:"btn btn-sm btn-default" %>
        <%= link_to 'edit', edit_admin_category_path(category), class:"btn btn-sm btn-warning" %>
        <%= link_to 'delete', admin_category_path(category), method: :delete, class:"btn btn-sm btn-danger" %>
        <%= link_to 'new SC', new_admin_category_sub_category_path(category), class:"btn btn-sm btn-info" %>

      </td>
    </tr>
    <tr>
      <td class="accordion-body collapse" id="<%= category.name %>-cores">
        <table class="table table-sm">
          <thead>
            <th>SubCat Name (click to toggle)</th>
            <th>SubCat ID</th>
            <th>Actions</th>
          </thead>
          <tbody>

          <% @sub_categories.where("category_id": category.id).each do |subcategory| %>

            <tr class="accordion-toggle" data-toggle="collapse" data-target="#<%= subcategory.name %>-cores">
              <td><%= subcategory.name %></td>
              <td><%= subcategory.id %></td>
              <td>
                <%= link_to 'show', admin_category_sub_category_path(category, subcategory), class:"btn btn-sm btn-default" %>
                <%= link_to 'edit', edit_admin_category_sub_category_path(category, subcategory), class:"btn btn-sm btn-warning" %>
                <%= link_to 'delete', admin_category_sub_category_path(category, subcategory), method: :delete, class:"btn btn-sm btn-danger" %>
                <%= link_to 'new SSC', new_admin_category_sub_category_sub_sub_category_path(category, subcategory), class:"btn btn-sm btn-info" %>

              </td>
            </tr>
            <tr>
              <td class="accordion-body collapse" id="<%= subcategory.name %>-cores">
                <table class="table table-sm">
                  <thead>
                    <th>SubSubCat Name</th>
                    <th>SubSubCat ID</th>
                    <th>Actions</th>
                  </thead>
                  <tbody>

                    <% @sub_sub_categories.where("sub_category_id": subcategory.id).each do |subsubcategory| %>

                    <tr>
                      <td><%= subsubcategory.name %></td>
                      <td><%= subsubcategory.id %></td>
                      <td>
                        <%= link_to 'show', admin_category_sub_category_sub_sub_category_path(category, subcategory, subsubcategory), class:"btn btn-sm btn-default" %>
                        <%= link_to 'edit', edit_admin_category_sub_category_sub_sub_category_path(category, subcategory, subsubcategory), class:"btn btn-sm btn-warning" %>
                        <%= link_to 'delete', admin_category_sub_category_sub_sub_category_path(category, subcategory, subsubcategory), method: :delete, class:"btn btn-sm btn-danger" %>
                      </td>
                    </tr>

                  <% end %>

                  </tbody>
                </table>
              </td>
            </tr>

          <% end %>

          </tbody>
        </table>
      </td>
    </tr>
<% end %>

  </tbody>
</table>

app/views/admin/categories/new.html.erb
<%= render 'admin/main/header' %>

<div class="form-container" style="width: 60%">
  <h1>Create New Category</h1>

  <%= @category.errors.full_messages %>

  <%= form_for @category, url: admin_categories_path do |f| %>


    <div class="form-group">
    	<%= f.label :name %>
    	<%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
    	<%= f.submit :class => "btn btn-default"%>
    </div>


  <% end %>

  <br><br>

  <%= link_to 'Back to Categories', admin_categories_path %>
  <br>
  <%= link_to 'Back to All Products', admin_root_path %>

</div>

app/views/admin/categories/show.html.erb
<%= render 'admin/main/header' %>

<h1>All Products with Category: <%= @category.name %></h1>


<% @products.each do |product| %>
<div class="col-md-4" style="padding: 0px 20px; height: 400px">
  <h1>
    <a href="/admin/products/<%= product.id %>" style="color: black"><%= product.name %></a>
      <small>
        <%= product.price %>
      </small>
  </h1>
  <p>
    <%= product.description %>
  </p>


</div>

<% end %>

app/views/admin/products/edit.html.erb
<%= render 'admin/main/header' %>

<div class="form-container" style="width: 60%">
  <h1>Edit Product</h1>

  <%= form_for @product, url: admin_product_path(params[:id]) do |f| %>


    <div class="form-group">
    	<%= f.label :name %>
    	<%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :price %>
      <%= f.number_field :price, value: number_with_precision(f.object.price, precision: 2), class: "form-control" %>
    </div>
    <div class="form-group">
    	<%= f.label :description %>
    	<%= f.text_area :description, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :sub_sub_category_id %>
      <%= f.collection_select(:sub_sub_category_id, SubSubCategory.all, :id, :name)%>

    </div>

    <div class="form-group">
    	<%= f.submit :class => "btn btn-default"%>
    </div>


  <% end %>

  <br><br>

  <%= link_to 'Back to Product', admin_product_path %>
  <br>
  <%= link_to 'Back to All Products', admin_root_path %>

</div>

app/views/admin/products/new.html.erb
<%= render 'admin/main/header' %>

<div class="form-container" style="width: 60%">
  <h1>Create New Product</h1>

  <%= @product.errors.full_messages %>

  <%= form_for @product, url: admin_products_path do |f| %>


    <div class="form-group">
    	<%= f.label :name %>
    	<%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :price %>
      <%= f.number_field :price, value: number_with_precision(f.object.price, precision: 2), class: "form-control" %>
    </div>
    <div class="form-group">
    	<%= f.label :description %>
    	<%= f.text_area :description, class: "form-control", placeholder: "min 140 characters!" %>
    </div>

    <div class="form-group">
      <%= f.label :sub_sub_category_id %>
      <%= f.collection_select(:sub_sub_category_id, SubSubCategory.all, :id, :name)%>

    </div>

    <div class="form-group">
    	<%= f.submit :class => "btn btn-default"%>
    </div>


  <% end %>


  <br><br>

  <button type="button" class="btn btn-lg btn-default"><%= link_to 'Back to All Products', admin_root_path %></button>

</div>

app/views/admin/products/show.html.erb
<%= render 'admin/main/header' %>

<h1>
<a href="/admin/categories/<%= @category.id %>"><%= @category.name %></a> >
<a href="/admin/categories/<%= @category.id %>/sub_categories/<%= @sub_category.id %>"><%= @sub_category.name %></a> >
<a href="/admin/categories/<%= @category.id %>/sub_categories/<%= @sub_category.id %>/sub_sub_categories/<%= @sub_sub_category.id %>"><%= @sub_sub_category.name %></a> >
<%= @product.name %>
</h1>

  <div class="col-md-12" style="background-color: white; padding: 0px 20px; margin-bottom: 10px">
    <h1>
      <%= @product.name %>
        <small>
          <%= @product.price %>
        </small>
    </h1>
    <p>
      <%= @product.description %>
    </p>

    <%= link_to 'edit', edit_admin_product_path(@product), class:"btn btn-lg" %>
    <%= link_to 'delete', admin_product_path(@product), method: :delete, class:"btn btn-lg" %>

  </div>

app/views/categories/show.html.erb
<%= render 'main/header' %>

<h1><%= @category.name %></h1>
<h3>
<% @sub_category.each do |subcat| %>
  | <a href="<%= @category.id %>/sub_categories/<%= subcat.id %>"><%= subcat.name %></a>
<% end %>
</h3>

<% @products.each do |product| %>
  <div class="col-md-4" style="padding: 0px 20px; height: 400px">
    <h1>
      <a href="/products/<%= product.id %>" style="color: black"><%= product.name %></a>
        <small>
          <%= product.price %>
        </small>
    </h1>
    <p>
      <%= product.description %>
    </p>
  </div>
<% end %>

app/views/products/show.html.erb
<%= render 'main/header' %>
<h1>
<a href="/categories/<%= @category.id %>"><%= @category.name %></a> >
<a href="/categories/<%= @category.id %>/sub_categories/<%= @sub_category.id %>"><%= @sub_category.name %></a> >
<a href="/categories/<%= @category.id %>/sub_categories/<%= @sub_category.id %>/sub_sub_categories/<%= @sub_sub_category.id %>"><%= @sub_sub_category.name %></a> >
<%= @product.name %>
</h1>



  <div class="col-md-12" style="background-color: white; padding: 0px 20px; margin-bottom: 10px">
    <h1>
      <%= @product.name %>
        <small>
          <%= @product.price %>
        </small>
    </h1>
    <p>
      <%= @product.description %>
    </p>
  </div>